// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHjjUtZxLmSa9XEDq-6-Z9-Yr6NEYh3x0',
    appId: '1:526907265682:web:4f0552b2c4090e96b8cc4b',
    messagingSenderId: '526907265682',
    projectId: 'pengayaan-24',
    authDomain: 'pengayaan-24.firebaseapp.com',
    storageBucket: 'pengayaan-24.appspot.com',
    measurementId: 'G-94SNRB9XB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfTDRZRXr-iIO4BSjzt-KZbxPjPckAuB4',
    appId: '1:526907265682:android:480d2255b827e822b8cc4b',
    messagingSenderId: '526907265682',
    projectId: 'pengayaan-24',
    storageBucket: 'pengayaan-24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0YXaLu0spgIl2Aw1vHUfodnSXQSfWmz4',
    appId: '1:526907265682:ios:b8f1937ef189025cb8cc4b',
    messagingSenderId: '526907265682',
    projectId: 'pengayaan-24',
    storageBucket: 'pengayaan-24.appspot.com',
    iosBundleId: 'com.example.miniproject3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0YXaLu0spgIl2Aw1vHUfodnSXQSfWmz4',
    appId: '1:526907265682:ios:b8f1937ef189025cb8cc4b',
    messagingSenderId: '526907265682',
    projectId: 'pengayaan-24',
    storageBucket: 'pengayaan-24.appspot.com',
    iosBundleId: 'com.example.miniproject3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHjjUtZxLmSa9XEDq-6-Z9-Yr6NEYh3x0',
    appId: '1:526907265682:web:3f805ae0f4d71411b8cc4b',
    messagingSenderId: '526907265682',
    projectId: 'pengayaan-24',
    authDomain: 'pengayaan-24.firebaseapp.com',
    storageBucket: 'pengayaan-24.appspot.com',
    measurementId: 'G-YC4HE2QEDK',
  );
}
